nebius/soperator

README.md
docs/architecture.md
docs/future_plans.md
docs/limitations.md

Update shields & make images take up the whole width

---

README.md

I took the content from this PR originally submitted by @iglunchadze but solved the merge conflicts.
Plus, I added the link to the Medium article.

Initial readme editing

---

api/v1/slurmcluster_types.go
config/crd/bases/slurm.nebius.ai_slurmclusters.yaml
helm/soperator-crds/templates/slurmcluster-crd.yaml
helm/soperator/crds/slurmcluster-crd.yaml
internal/render/accounting/container.go
internal/render/benchmark/container.go
internal/render/benchmark/container_test.go
internal/render/common/container.go
internal/render/controller/container.go
internal/render/login/container.go
internal/render/populate_jail/container.go
internal/render/prometheus/container.go
internal/render/worker/container.go
internal/values/slurm_jail.go
internal/values/slurm_periodic_checks.go
internal/values/slurm_worker.go

Hi people, I have added an extra field `ImagePullPolicy` in specs, so we can avoid always pulling images from the cloud.

feat: support ImagePullPolicy from manifest

---

internal/render/accounting/container.go
internal/render/accounting/mariadb.go
internal/render/common/container.go
internal/render/common/limits.go
internal/render/common/resources.go
internal/render/controller/container.go
internal/render/login/container.go
internal/render/prometheus/container.go
internal/render/worker/container.go
internal/render/worker/container_test.go

fix required value Limit must be set for non overcommitable  resource and if limits empty  pass to empty resource list

hotfix: fix required Limit must be set for non overcommitable 

---

.github/workflows/gpubench_only.yml
.github/workflows/one_job.yml

We do not test gpubench when making changes, nor is it necessary to build the entire package when there are changes in gpubench.

NOTASK: test gpubench

---

api/v1/slurmcluster_types.go
config/crd/bases/slurm.nebius.ai_slurmclusters.yaml
helm/soperator-crds/templates/slurmcluster-crd.yaml
helm/soperator/crds/slurmcluster-crd.yaml

```
~# sacct --format=JobID,JobName,AllocCPUS,MaxRSS,MaxVMSize,TotalCPU,State
JobID           JobName  AllocCPUS     MaxRSS  MaxVMSize   TotalCPU      State 
------------ ---------- ---------- ---------- ---------- ---------- ---------- 
19.0              sleep          2      6040K          0  00:00.004  COMPLETED 
20                sleep          2                        00:00.004     FAILED 
20.0              sleep          2      5872K          0  00:00.004     FAILED 
21                sleep          2                        00:00.004     FAILED 
21.0              sleep          2      5868K          0  00:00.004     FAILED 
22                sleep          2                        00:00.004  COMPLETED 
22.0              sleep          2      6036K          0  00:00.004  COMPLETED …
```

MSP-3516: settings of accounting to scrape jobs stats

---

images/accounting/slurmdbd_entrypoint.sh
images/common/scripts/install_docker.sh
images/common/scripts/install_docker_cli.sh
images/controller/slurmctld_entrypoint.sh
images/jail/scripts/createuser.sh
images/login/sshd_entrypoint.sh
images/munge/munge_entrypoint.sh
images/nccl_benchmark/nccl_benchmark_entrypoint.sh
images/nccl_benchmark/scripts/srun_perf.sh
images/restd/slurmrestd_entrypoint.sh
images/worker/scripts/gpu_healthcheck.sh
images/worker/slurmd_entrypoint.sh
images/worker/supervisord_entrypoint.sh

Revert "Print actual command before executing it in bash scripts"

---

cmd/main.go
internal/controller/clustercontroller/reconcile.go

Currently, if `WATCH_NAMESPACE` is used, the controller still makes a list request to the kube-apiserver for all namespaces, which is an overhead. Additionally, it has been fixed so that `WATCH_NAMESPACE` is no longer used; instead, `SLURM_OPERATOR_WATCH_NAMESPACES` is introduced.

Change watching ns mechanism

---

images/jail/jail.dockerfile
images/jail/pin_packages/cuda-pins
images/jail/skel/.profile

https://github.com/nebius/soperator/issues/384

Preinstall Nvidia mock packages issues/384

---

images/jail/jail.dockerfile

https://github.com/nebius/soperator/issues/380

Preinstall dcgmi tools to the jail

---

PROJECT
api/v1alpha1/groupversion_info.go
api/v1alpha1/nodeconfigurator_types.go
cmd/main.go
config/crd/kustomization.yaml
config/rbac/kustomization.yaml
config/rbac/nodeconfigurator_admin_role.yaml
config/rbac/nodeconfigurator_editor_role.yaml
config/rbac/nodeconfigurator_viewer_role.yaml
config/samples/kustomization.yaml
config/samples/slurm_v1alpha1_nodeconfigurator.yaml
internal/controller/nodeconfigurator_controller.go
internal/controller/suite_test.go

kubebuilder create api --group slurm --version v1alpha1 --kind NodeConfigurator #404

---

internal/checkcontroller/k8s_nodes_controller.go
internal/checkcontroller/reconcile.go
internal/checkcontroller/slurm_workers_controller.go
internal/consts/conditions.go

K8S nodes controller to handle slurm node conditions

398: Add k8s nodes controller

---

.codespellrc
.github/workflows/codespell.yml
api/v1alpha1/nodeconfigurator_types.go
config/crd/bases/slurm.nebius.ai_nodeconfigurators.yaml
config/crd/bases/slurm.nebius.ai_slurmclusters.yaml
config/crd/slurm.nebius.ai_slurmclusters.yaml
docs/future_plans.md
helm/soperator-crds/templates/slurmcluster-crd.yaml
helm/soperator/crds/slurmcluster-crd.yaml
images/common/enroot/enroot.conf
images/restd/slurmrestd.dockerfile
images/worker/gpubench/main.go
images/worker/supervisord_entrypoint.sh
internal/controller/clustercontroller/reconcile.go
internal/render/common/resources.go

More about codespell: https://github.com/codespell-project/codespell .
I personally introduced it to dozens if not hundreds of projects already and so far only positive feedback.
CI workflow has 'permissions' set only to 'read' so also should be safe.

Add codespell support (config, workflow to detect/not fix) and make it fix few typos

---

helm/nodeconfigurator/values.yaml
helm/slurm-cluster-storage/templates/accounting-mount-daemonset.yaml
helm/slurm-cluster-storage/templates/controller-spool-mount-daemonset.yaml
helm/slurm-cluster-storage/templates/jail-mount-daemonset.yaml
helm/slurm-cluster-storage/templates/jail-submounts-mount-daemonset.yaml
images/accounting/slurmdbd.dockerfile
images/controller/slurmctld.dockerfile
images/exporter/exporter.dockerfile
images/jail/jail.dockerfile
images/login/sshd.dockerfile
images/munge/munge.dockerfile
images/nccl_benchmark/nccl_benchmark.dockerfile
images/populate_jail/populate_jail.dockerfile
images/restd/slurmrestd.dockerfile
images/worker/slurmd.dockerfile
internal/render/nodeconfigurator/container.go
internal/values/slurm_worker.go

Use Nebius container mirrored images because of docker hub limits

---

.github/workflows/gpubench_only.yml
images/worker/gpubench/go.mod
images/worker/gpubench/main.go
images/worker/gpubench/main_test.go

[#480](https://github.com/nebius/soperator/issues/480)

480: do not run nccl test if some proccess running on gpus

---

internal/render/common/configmap.go

fix "srun: s_p_parse_file: file /etc/slurm/custom_slurm.conf is empty" message in every srun command

Add comment in the beginning of custom_slurm.conf file

---

PROJECT
api/v1/slurmcluster_types.go
api/v1alpha1/nodeconfigurator_types.go
api/v1alpha1/nodeset_types.go
cmd/main.go
config/crd/bases/kustomization.yaml
config/crd/bases/slurm.nebius.ai_nodesets.yaml
config/crd/kustomization.yaml
config/rbac/clustercontroller/role.yaml
config/rbac/kustomization.yaml
config/rbac/nodeset_admin_role.yaml
config/rbac/nodeset_editor_role.yaml
config/rbac/nodeset_viewer_role.yaml
config/samples/kustomization.yaml
config/samples/slurm_v1alpha1_nodeset.yaml
hack/boilerplate.go.txt
helm/soperator-crds/templates/slurmcluster-crd.yaml
helm/soperator/crds/slurmcluster-crd.yaml
helm/soperator/templates/manager-rbac.yaml
internal/controller/clustercontroller/reconcile.go
internal/controller/fixtures_test.go
internal/controller/nodeconfigurator/nodeconfigurator_controller.go
internal/controller/nodesetcontroller/controller.go
internal/controller/nodesetcontroller/controller_test.go
internal/controller/nodesetcontroller/indexer.go
internal/controller/nodesetcontroller/nodeset_controller.go
internal/controller/nodesetcontroller/nodeset_controller_test.go
internal/logfield/fields.go
internal/logfield/resource.go

This PR is a first stage of #487

NodeSet Controller origin

---

cmd/sconfigcontroller/main.go
internal/controller/sconfigcontroller/controller.go
internal/controller/sconfigcontroller/controller_test.go

- Created skeleton for the sconfigcontroller
- Used cache with namespace and label filtering
- Fixed rbac generation bug. All controllers from internal/controller were placed under manager-role

508: Added initial setup for sconfigcontroller

---

Makefile
config/rbac/clustercontroller/role.yaml
helm/soperator/templates/manager-rbac.yaml

Fixing the impact of this PR:
https://github.com/nebius/soperator/pull/541

Adding autogeneration of rbacs for nodeconfigurator and clustercontroller

---

fluxcd/enviroment/local/soperator-kind/kustomization.yaml
fluxcd/enviroment/nebius-cloud/soperator-infra/kustomization.yaml
fluxcd/enviroment/nebius-cloud/soperator/kustomization.yaml

[fluxcd] delete git repo from kustomize #617

---

fluxcd/base/nodeconfigurator/kustomization.yaml
fluxcd/base/nodeconfigurator/resources.yaml
fluxcd/base/soperator/kustomization.yaml
fluxcd/base/soperator/resources.yaml
fluxcd/base/soperatorchecks/kustomization.yaml
fluxcd/base/soperatorchecks/resources.yaml
fluxcd/enviroment/local/base/kustomization.yaml
fluxcd/enviroment/nebius-cloud/base/kustomization.yaml

[fluxcd] add soperator helm chart to fluxcd #617

---

fluxcd/base/security-profiles-operator/kustomization.yaml
fluxcd/base/security-profiles-operator/resources.yaml
fluxcd/enviroment/nebius-cloud/base/kustomization.yaml

[fluxcd] add security-profiles-operator helm release #643

---

fluxcd/base/cert-manager/kustomization.yaml
fluxcd/base/cert-manager/resources.yaml
fluxcd/base/nodeconfigurator/resources.yaml
fluxcd/base/opentelemetry-collector-events/resources.yaml
fluxcd/base/opentelemetry-collector-logs/resources.yaml
fluxcd/base/security-profiles-operator/resources.yaml
fluxcd/base/slurm-cluster/resources.yaml
fluxcd/base/soperator/resources.yaml
fluxcd/base/victoria-metrics-operator/resources.yaml
fluxcd/enviroment/nebius-cloud/base/kustomization.yaml

#646 add cert-manager flux and fix HelmRepository names

---

fluxcd/base/mariadb-operator/kustomization.yaml
fluxcd/base/mariadb-operator/resources.yaml
fluxcd/enviroment/local/base/kustomization.yaml
fluxcd/enviroment/nebius-cloud/base/kustomization.yaml

[fluxcd] add mariadb operator #645

---

fluxcd/base/gpu-operator/resources.yaml
fluxcd/base/mariadb-operator/resources.yaml
fluxcd/base/namespaces/kustomization.yaml
fluxcd/base/namespaces/resources.yaml
fluxcd/base/security-profiles-operator/resources.yaml
fluxcd/base/slurm-cluster-storage/resources.yaml
fluxcd/base/soperator/resources.yaml
fluxcd/base/victoria-logs/resources.yaml
fluxcd/base/victoria-metrics-operator/resources.yaml
fluxcd/enviroment/local/base/kustomization.yaml
fluxcd/enviroment/nebius-cloud/base/kustomization.yaml

[fluxcd] add ns to Kustomization #653

---

.golangci.yaml

Comment linters.

---

.golangci.yaml
internal/controller/reconciler/k8s_statefulset_test.go
internal/rebooter/reconcile.go

Turn on errcheck linter.

---

fluxcd/base/slurm-cluster/resources.yaml

[fluxcd] fix slurm cluster values #653

---

fluxcd/base/security-profiles-operator/resources.yaml

[fluxcd] fix version spo #653

---

fluxcd/base/mariadb-operator/resources.yaml

[fluxcd] fix version mariadb

---

Makefile
helm/soperator-fluxcd/.helmignore
helm/soperator-fluxcd/Chart.yaml
helm/soperator-fluxcd/templates/_helpers.tpl
helm/soperator-fluxcd/templates/cert-manager.yaml
helm/soperator-fluxcd/templates/helmrepository.yaml
helm/soperator-fluxcd/templates/k8up.yaml
helm/soperator-fluxcd/templates/mariadb-operator-crds.yaml
helm/soperator-fluxcd/templates/mariadb-operator.yaml
helm/soperator-fluxcd/templates/nodeconfigurator.yaml
helm/soperator-fluxcd/templates/ns.yaml
helm/soperator-fluxcd/templates/opentelemetry-collector-events.yaml
helm/soperator-fluxcd/templates/opentelemetry-collector-logs.yaml
helm/soperator-fluxcd/templates/prometheus-operator-crds.yaml
helm/soperator-fluxcd/templates/security-profiles-operator.yaml
helm/soperator-fluxcd/templates/slurm-cluster-storage.yaml
helm/soperator-fluxcd/templates/slurm-cluster.yaml
helm/soperator-fluxcd/templates/soperator.yaml
helm/soperator-fluxcd/templates/soperatorchecks.yaml
helm/soperator-fluxcd/templates/victoria-metrics-operator-crds.yaml
helm/soperator-fluxcd/templates/vm-logs.yaml
helm/soperator-fluxcd/templates/vm-stack.yaml
helm/soperator-fluxcd/values.yaml

[fluxcd] umbrella chart for helm release #746

---

.github/workflows/e2e_test.yml
test/e2e/e2e_test.go

Upload artifacts for logs to split terraform output from terraform errors

reduce logs in e2e

---

helm/slurm-cluster/templates/pvc.yaml
helm/slurm-cluster/values.yaml

for  https://github.com/nebius/soperator/issues/847
Added PVC templating mechanism for faster bootstraping and clear resource management.

Added templated PVC

---

fluxcd/environment/nebius-cloud/base/custom-configmaps-soperator/daemon.json
fluxcd/environment/nebius-cloud/base/custom-configmaps-soperator/enroot.conf
fluxcd/environment/nebius-cloud/base/custom-configmaps-soperator/kustomization.yaml

add image-storage to kustomize #653

---

helm/soperator-fluxcd/templates/vm-stack.yaml
helm/soperator-fluxcd/values.yaml

add grafana.password #653

---

helm/soperator-fluxcd/values.yaml

add remoteWrite to nebius #771

---

images/accounting/slurmdbd.dockerfile

Install deb packages from Nebius deb repo for accounting image with slurm 24.05.7

---

images/controller/slurmctld.dockerfile

Install deb packages from Nebius deb repo for slurm controller image with slurm 24.05.7

---

images/exporter/exporter.dockerfile

Install deb packages from Nebius deb repo for slurm exporter image with slurm 24.05.7

---

helm/soperator-fluxcd/templates/opentelemetry-collector-events.yaml
helm/soperator-fluxcd/templates/opentelemetry-collector-logs.yaml

bump o11y image  #787

---

images/common/scripts/install_container_toolkit.sh
images/common/scripts/install_docker_cli.sh
images/common/scripts/install_openmpi.sh
images/common/scripts/install_python.sh
images/jail/jail.dockerfile
images/worker/slurmd.dockerfile

Install deb packages from Nebius deb repo for jail image with slurm 24.05.7

---

images/common/scripts/install_munge.sh
images/nccl_benchmark/nccl_benchmark.dockerfile

Install packages from Nebius deb registry for nccl_benchmark docker image

---

images/populate_jail/populate_jail.dockerfile

Change base image for populate_jail image

---

helm/soperator-fluxcd/templates/opentelemetry-collector-logs.yaml

Send `syslog`, `kern.log`, `dmesg.log` to Nebius o11y #787

---

images/slurm_check_job/slurm_check_job.dockerfile

Install deb packages from Nebius deb repo for slurm check image with slurm 24.05.7

---

helm/soperator-fluxcd/templates/opentelemetry-collector-logs.yaml

add collect fabricmanager.log #771

---

fluxcd/environment/nebius-cloud/base/custom-configmaps-soperator/95-nebius-o11y
helm/soperator-fluxcd/templates/vm-stack.yaml
helm/soperator-fluxcd/values.yaml

https://github.com/nebius/soperator/issues/910

Remove Grafana Auth

---

cmd/main.go
internal/consts/configmap.go
internal/consts/label.go
internal/controller/topologyconfcontroller/base_reconciler.go
internal/controller/topologyconfcontroller/nodetopology_controller.go
internal/controller/topologyconfcontroller/nodetopology_controller_test.go

#668
[#427](https://github.com/nebius/soperator/issues/427)

[topology-aware] add topologyconfcontroller #427

---

Makefile
config/rbac/clustercontroller/role.yaml
helm/soperator/templates/manager-rbac.yaml
internal/controller/topologyconfcontroller/nodetopology_controller.go

add rbac list node to soperator nodetopology #427

---

api/v1/slurmcluster_types.go
config/crd/bases/slurm.nebius.ai_slurmclusters.yaml
helm/soperator-crds/templates/slurmcluster-crd.yaml
helm/soperator/crds/slurmcluster-crd.yaml
internal/render/common/configmap.go

For SchedulerParameters, HealthCheckNodeState, TCPTimeout and MessageTimeout

Change default slurm config values

---

helm/soperator-fluxcd/templates/opentelemetry-collector-logs.yaml
helm/soperator-fluxcd/values.yaml

[logs] collect logs from hc and prolog #975

---

helm/soperator-fluxcd/templates/vm-stack.yaml

[fix] vmagent scrape kubelet metrics with large lables per node

---

cmd/sconfigcontroller/main.go
images/common/scripts/bind_slurm_common.sh
images/common/scripts/complement_jail.sh
images/controller/slurmctld_entrypoint.sh
images/jail/jail.dockerfile
images/nccl_benchmark/nccl_benchmark_entrypoint.sh
images/slurm_check_job/slurm_check_job_entrypoint.sh
images/worker/supervisord_entrypoint.sh
images/worker/wait-for-controller.sh
internal/controller/clustercontroller/reconcile.go
internal/controller/sconfigcontroller/controller.go
internal/controller/sconfigcontroller/controller_test.go
internal/controller/topologyconfcontroller/workertopology_controller.go
internal/render/sconfigcontroller/initcontainer.go
internal/render/sconfigcontroller/role.go

[fix] fix events to sconfigcontroller and replace get to list

---

.gitignore
Makefile
helm/slurm-cluster/values.yaml
helm/soperator-activechecks/values.yaml
images/accounting/slurmdbd.dockerfile
images/common/scripts/install_openmpi.sh
images/common/scripts/install_python.sh
images/controller/slurmctld.dockerfile
images/exporter/exporter.dockerfile
images/jail/jail.dockerfile
images/k8s_check_job/k8s_check_job.dockerfile
images/login/sshd.dockerfile
images/munge/munge.dockerfile
images/populate_jail/populate_jail.dockerfile
images/restd/slurmrestd.dockerfile
images/slurm_check_job/slurm_check_job.dockerfile
images/worker/slurmd.dockerfile

Upgrade on ubuntu noble

---

cmd/soperatorchecks/main.go
internal/consts/conditions.go
internal/controller/soperatorchecks/k8s_nodes_controller.go
internal/controller/soperatorchecks/k8s_nodes_controller_test.go

[soperatorchecks] Unknown status for Ready type of kubelet

---

cmd/sconfigcontroller/main.go
internal/controller/topologyconfcontroller/base_reconciler.go
internal/controller/topologyconfcontroller/nodetopology_controller.go
internal/controller/topologyconfcontroller/workertopology_controller.go

[nodeTopology] re-generate CM node topology if cm deleted.

---

api/v1/slurmcluster_types.go
config/crd/bases/slurm.nebius.ai_slurmclusters.yaml
helm/soperator-crds/templates/slurmcluster-crd.yaml
helm/soperator/crds/slurmcluster-crd.yaml
internal/render/controller/daemonset.go
internal/render/controller/daemonset_test.go
internal/render/controller/statefulset.go
internal/render/controller/statefulset_test.go
internal/values/slurm_controller.go

A fix for why the controller is not setting the default priority class.

fix priorityclass name for controller

---

helm/soperator-fluxcd/templates/helmrelease-trigger-operator.yaml
helm/soperator-fluxcd/values.yaml

Updating the HelmRelease controller to the new Helm and container image.
https://github.com/nebius/soperator/issues/1412

change helmReleaseTriggerOperator

---

cmd/main.go
internal/controller/topologyconfcontroller/nodetopology_controller.go
internal/controller/topologyconfcontroller/nodetopology_controller_test.go

https://github.com/kubernetes-sigs/controller-runtime/issues/3044

Fix pagination issue in cache

---

.github/workflows/one_job.yml
internal/controller/soperatorchecks/slurm_nodes_controller.go

fix getting error when [user_problem] reason #1468

---

internal/render/accounting/pod.go
internal/render/controller/daemonset.go
internal/render/controller/statefulset.go
internal/render/exporter/pod.go
internal/render/login/statefulset.go
internal/render/nodeconfigurator/pod.go
internal/render/populate_jail/job.go
internal/render/prometheus/pod.go
internal/render/rest/pod.go
internal/render/sconfigcontroller/pod.go
internal/render/soperatorchecks/pod.go
internal/render/worker/statefulset.go

`hostUsers` must be false to use `Unmasked`

---

api/v1alpha1/activecheck_types.go
api/v1alpha1/jailedconfig_types.go
api/v1alpha1/nodeconfigurator_types.go
config/crd/bases/slurm.nebius.ai_activechecks.yaml
config/crd/bases/slurm.nebius.ai_jailedconfigs.yaml
config/crd/bases/slurm.nebius.ai_nodeconfigurators.yaml
helm/soperator-crds/templates/slurmcluster-crd.yaml
helm/soperator/crds/slurmcluster-crd.yaml

```
k -n soperator get activechecks.slurm.nebius.ai            
NAME                                 TYPE       K8S JOB STATUS   SLURM JOB STATUS   LAST JOB               LAST JOB ID   AGE
all-reduce-perf-nccl                 slurmJob                    Complete           all-reduce-perf-nccl   67            5d23h
create-user-nebius                   k8sJob     Complete                                                                 6d
create-user-soperatorchecks-action   k8sJob     Complete                                                                 6d
enroot-cleanup                       slurmJob                    Complete           enroot-cleanup         65            5d23h
soperator-outputs-logs-cleaner       k8sJob     Complete …
```

add  activechecks PrinterColumns

---

images/common/spank-nccl-debug/Makefile
images/common/spank-nccl-debug/README.md
images/common/spank-nccl-debug/src/snccld.c
images/common/spank-nccl-debug/src/snccld_state.c
images/common/spank-nccl-debug/src/snccld_util_dir_file.c
images/common/spank-nccl-debug/src/snccld_util_dir_file.h
images/common/spank-nccl-debug/src/snccld_util_oplock.c

1. Get mode from `stat`
2. Don't fail on `EPERM`
---
Made redeployment easier.

[nccl-debug] Don't try chmodding files and directories without a need

---

helm/soperator-activechecks/scripts/upgrade-health-checker.sh
helm/soperator-activechecks/templates/all-reduce-perf-nccl-with-ib.yaml
helm/soperator-activechecks/templates/all-reduce-perf-nccl-without-ib.yaml
helm/soperator-activechecks/templates/create-user-soperatorchecks.yaml
helm/soperator-activechecks/templates/create-user.yaml
helm/soperator-activechecks/templates/cuda-samples.yaml
helm/soperator-activechecks/templates/dcgmi-diag-r2.yaml
helm/soperator-activechecks/templates/dcgmi-diag-r3.yaml
helm/soperator-activechecks/templates/enroot-cleanup.yaml
helm/soperator-activechecks/templates/ensure-dir-snccld-logs.yaml
helm/soperator-activechecks/templates/extensive-check.yaml
helm/soperator-activechecks/templates/gpu-fryer.yaml
helm/soperator-activechecks/templates/ib-perf.yaml
helm/soperator-activechecks/templates/install-package.yaml
helm/soperator-activechecks/templates/mem-perf.yaml
helm/soperator-activechecks/templates/prepull-container-image.yaml
helm/soperator-activechecks/templates/soperator-outputs-logs-cleaner.yaml
helm/soperator-activechecks/templates/ssh-check.yaml
helm/soperator-activechecks/templates/upgrade-cuda.yaml
helm/soperator-activechecks/templates/upgrade-health-checker.yaml
helm/soperator-activechecks/templates/wait-for-topology.yaml
helm/soperator-activechecks/values.yaml
test/e2e/e2e_test.go

Made some values (`suspend`, `runAfterCreation`) configurable for every check inside ActiveChecks chart

Configurable values for ActiveChecks chart
