nebius/soperator

helm/slurm-cluster/templates/_helpers.tpl
Cluster names containing digits get kebabed at the start of each digit
**Example**:
`slurm-e2e` gets transformed to `slurm-e-2e`
=> [FIX] Cluster name altering

internal/render/common/container.go, internal/render/common/resources.go, internal/render/worker/container.go, internal/render/worker/container_test.go
For Slurm, it's necessary to use cpuset in cgroups. [Slurm Cgroups Documentation](https://slurm.schedmd.com/cgroups.html). In Kubernetes, cpuset is only created if a pod has a QoS of Guaranteed. [Kubernetes CPU Management Policies](https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/#static-policy).
Related issue: [kubernetes/kubernetes#85764](https://github.com/kubernetes/kubernetes/issues/85764)
=> HOTFIX: make worker pod as a Guaranteed

images/common/scripts/complement_jail.sh
Support mounting a single file to jail. For example, if we define volumes and mounts as follows, codes won't work before this PR.
```yaml
...
volumeSources:
- name: controller-spool
persistentVolumeClaim:
claimName: "controller-spool-pvc"
readOnly: false
- name: jail
persistentVolumeClaim:
claimName: "jail-pvc"
readOnly: false
- name: gpfs-dataset
hostPath:
path: /gpfs/benchmark
type: Directory
- name: gpfs-image
hostPath:
path: /gpfs/nemofw-training-2403.tar
type: File
...
...
volumes:
jail:
volumeSourceName: "jail"
jailSubMounts:
- name: "gpfs-bench-dataset"
mountPath: "/benchmark"
volumeSourceName: "gpfs-dataset"
- name: "gpfs-bench-image"
mountPath: "/images/nemofw-training-2403.tar"
volumeSourceName: "gpfs-image"
...
```
```
Starting slurmd entrypoint script
Link users from jail
Link …
```
=> bug: support jail sub-mounting single file

README.md, images/common/scripts/complement_jail.sh
rest.RenderSecret renders the cluster name as the namespace. This should be explicit in the README.
https://github.com/nebius/soperator/blob/8766049c7852fad947ddf1831928f640774d7967/internal/controller/clustercontroller/common.go#L55
=> docs(README): deploy slurm cluster in a namespace aligned with the cluster name

internal/render/worker/container.go
removed privileged rights and reduced them to minimal values for the DaemonSet sysctl for security reasons.
=> MSP-3851: remove privilages rights from sleep container sysctl

internal/controller/clustercontroller/accounting.go
Do not delete the MariaDB secret if `ProtectedSecret` is set to `true` when deleting the CR `slurmcluster`.
=> MSP-3868: delete ownerReferences for mariadb secrets

images/jail/gpubench/main.go
```
k -n slurm logs test3-4mt9j | sed 's/\\n/\n/g' 
Link users from jail
Bind-mount slurm configs from K8S config map
Bind-mount munge key from K8S secret
Starting munge
Waiting until munge started
Start NCCL test benchmark
8 GPUs on each node are going to be benchmarked
cpu-bind=MASK - worker-1, task  0  0 [4980]: mask 0xff00000000000000ff set
{"level":"info","msg":"Starting nccl-benchmark","slurmNode":"worker-1","time":"2025-01-03T09:37:10Z"}
{"error":"exit status 3","level":"fatal","msg":"Failed to execute all_reduce_perf","output":"
#
worker-1: Test NCCL failure common.cu:1005 'internal error - please report this issue to the NCCL developers / '
.. worker-1 pid 4990: Test failure common.cu:891
","slurmNode":"worker-1","time":"2025-01-03T09:37:18Z"}
srun: error: worker-1: task 0: …
```
=> gpubench add more informations in output

internal/controller/clustercontroller/accounting.go, internal/controller/clustercontroller/reconcile.go, internal/controller/reconciler/deployment.go, internal/controller/reconciler/grant.go, internal/controller/reconciler/k8s_role.go, internal/controller/reconciler/k8s_rolebinging.go, internal/controller/reconciler/k8s_service.go, internal/controller/reconciler/mariadb.go, internal/controller/reconciler/otel.go, internal/controller/reconciler/pod_monitor.go, internal/controller/reconciler/pod_monitor_test.go
This PR fixes the reconciliation logic to handle the scenario where maintenance is set to true and accounting is set to false. The changes ensure that the reconciliation process behaves correctly under these conditions, addressing any inconsistencies or errors observed previously.
=> MSP-3918: Fix bug reconciliation logic for scenarios with maintenance=true and accounting=false

api/v1/slurmcluster_types.go, config/crd/bases/slurm.nebius.ai_slurmclusters.yaml, helm/slurm-cluster/values.yaml, helm/soperator-crds/templates/slurmcluster-crd.yaml, helm/soperator/crds/slurmcluster-crd.yaml, internal/check/maintanence.go, internal/consts/maintenance.go, internal/controller/clustercontroller/populate_job.go, internal/controller/clustercontroller/reconcile.go, internal/render/populate_jail/container.go
This PR adds the ability to delete and recreate the `populateJob` with the overwrite option in Maintenance mode `downscaleAndOverwritePopulateJail`
=> add downscaleAndOverwritePopulateJail

internal/controller/reconciler/k8s_statefulset.go, internal/controller/reconciler/k8s_statefulset_test.go
When creating the StatefulSet, it was discovered that the StatefulSet is recreated twice, and during an update, the pod with the `-0` index is not updated. This happens because maps in Go are not merged.
=> MSP-3992: fix bug with empty version of annotation

.github/dependabot.yml, .github/workflows/gpubench_only.yml, .github/workflows/one_job.yml, images/worker/gpubench/go.mod, images/worker/gpubench/go.sum
CVE https://github.com/nebius/soperator/security/dependabot/8
=> bump golang.org/x/net to v0.33.0

cmd/main.go, internal/controller/clustercontroller/accounting.go, internal/controller/clustercontroller/benchmark.go, internal/controller/clustercontroller/common.go, internal/controller/clustercontroller/controller.go, internal/controller/clustercontroller/exporter.go, internal/controller/clustercontroller/login.go, internal/controller/clustercontroller/populate_job.go, internal/controller/clustercontroller/reconcile.go, internal/controller/clustercontroller/rest.go, internal/controller/clustercontroller/worker.go, internal/controller/reconciler/deployment.go, internal/controller/reconciler/grant.go, internal/controller/reconciler/k8s_role.go, internal/controller/reconciler/k8s_rolebinging.go, internal/controller/reconciler/k8s_service.go, internal/controller/reconciler/mariadb.go, internal/controller/reconciler/otel.go, internal/controller/reconciler/pod_monitor.go, internal/controller/reconciler/reconciler.go, internal/utils/mutltistep.go, internal/values/types.go, internal/values/validate.go
```
{
"level": "info",
"ts": "2025-01-24T11:50:36+01:00",
"msg": "Finished reconciliation of Slurm Cluster",
"controller": "slurmcluster",
"controllerGroup": "slurm.nebius.ai",
"controllerKind": "SlurmCluster",
"SlurmCluster": {
"name": "slurm",
"namespace": "slurm"
},
"namespace": "slurm",
"name": "slurm",
"reconcileID": "53453617-39ba-41f1-807d-89cad3e2c6c1"
}
{
"level": "debug",
"ts": "2025-01-24T11:50:36+01:00",
"msg": "Reconciliation state removed for object",
"controller": "slurmcluster",
"controllerGroup": "slurm.nebius.ai",
"controllerKind": "SlurmCluster",
"SlurmCluster": {
"name": "slurm",
"namespace": "slurm"
},
"namespace": "slurm",
"name": "slurm",
"reconcileID": "53453617-39ba-41f1-807d-89cad3e2c6c1",
"kind": "slurm.nebius.ai/v1, Kind=SlurmCluster",
"key": "slurm/slurm"
} …
```
=> NOTASK: add debug logs

images/common/scripts/complement_jail.sh, images/common/scripts/install_pyxis_plugin.sh, internal/render/common/configmap.go
Use new pyxis with options to save squashfs files and expose enroot logs.
Closes #396
=> Update pyxis version with `container_image_save` and `expose_enroot_logs` enagled

internal/render/common/configmap.go
This flag is currently breaking `srun --pty`
=> Temporary remove `expose_enroot_logs` flag

api/v1/slurmcluster_types.go, api/v1/zz_generated.deepcopy.go, config/crd/bases/slurm.nebius.ai_slurmclusters.yaml, helm/slurm-cluster/values.yaml, helm/soperator-crds/templates/slurmcluster-crd.yaml, helm/soperator/crds/slurmcluster-crd.yaml
**Prolog** and **Epilog** in Slurm are crucial for automating job setup and cleanup on compute nodes. 
- The Prolog script runs before a job starts, ensuring the environment is correctly configured, resources are prepared, and any necessary checks are performed. 
- The Epilog script runs after a job finishes, handling cleanup tasks like deleting temporary files, releasing resources, and logging job completion. 
These scripts help maintain node consistency, optimize resource utilization, and improve job management in HPC environments.
=> Add Epilog and Prolog options

images/worker/scripts/gpu_healthcheck.sh
When there's a GPU error, nvidia-smi will return with non-zero exit code in the forked shell of /usr/bin/gpu_healthcheck.sh, and given `set -e` option at line 3, it will inmediately exit.
This PR handles nvidia-smi error codes gracefully.
=> Fix non-zero error handling in gpu_healthcheck.sh

images/accounting/slurmdbd_entrypoint.sh, images/common/scripts/complement_jail.sh, images/controller/slurmctld_entrypoint.sh, images/nccl_benchmark/nccl_benchmark_entrypoint.sh, images/restd/slurmrestd_entrypoint.sh, images/worker/supervisord_entrypoint.sh
Jail configs are mounted as a directory, host ones replaced with symlinks.
It allows config updates with ConfigMap changes.
=> images: do not bind-mount slurm configs when possible

Makefile, config/rbac/clustercontroller/role.yaml, helm/soperator/templates/manager-rbac.yaml
There was a line in the Make file:
`$(CONTROLLER_GEN) rbac:roleName=manager-role paths="./internal/controller/..." `
Because of that, all controllers were generating their rbacs to the manager-role
=> Bugfix: Fixed all rbac generated under the same roleName

api/v1/slurmcluster_types.go, api/v1/zz_generated.deepcopy.go, config/crd/bases/slurm.nebius.ai_slurmclusters.yaml, helm/slurm-cluster/templates/slurm-cluster-cr.yaml, helm/slurm-cluster/values.yaml, helm/soperator-crds/templates/slurmcluster-crd.yaml, helm/soperator/crds/slurmcluster-crd.yaml, internal/render/worker/statefulset.go, internal/values/slurm_worker.go
Provide a new field for workerAnnotations in worker definition.
This workerAnnotations map will be added to the worker statefulset spec annotations for workers, so annotations required for workers only (like the ones for providing RoCE backend NICs) can be set.
=> Add workerAnnotations to worker definition

images/worker/gpubench/go.mod, images/worker/gpubench/main.go, images/worker/slurmd.dockerfile
This PR fixes an issue with resource synchronization in nebius/soperator by  version of golang and fix bug with parsing args
=> bump golang version to 1.24 and fix bug with parse of args

cmd/soperatorchecks/main.go, images/common/scripts/complement_jail.sh, images/common/scripts/install_nvidia_libs.sh, images/worker/slurmd.dockerfile
Instead of configuring Nvidia container on each worker, configure it once (using flock), and then next worker will only check the version using `nvidia-constainer-cli info` and do nothing. This will speed up this part from 2.5s to 0.5s, which is several minutes speedup for big enough clusters.
=> #618: Speedup nvidia driver configuration on the worker start

images/common/scripts/complement_jail.sh
`nvidia-container-cli configure` runs for 2-2.5s on average and it was run under `flock` only to prevent races during `ldconfig` calls (it failed which resulted in a pod restart).
Since `ldconfig` is run separately under other `flock`, it was removed from the configuration call with the flock altogether.
It should speed up the workers statefulset restart by 2-2.5s multiplied by the number of workers.
=> #618: [Speedup] Disable ldconfig on nvidia driver configuration.

.github/workflows/one_job.yml, .golangci.yaml, Makefile
Golangilint config migrated to v2 with `golangilint migrate` command most of the changes are from there:
looks like they dropped linter presets, that's why they were "unwrapped".
Also `cyclop` linter was disabled, blames about our code.
Adds 4s to the build time.
Closes #662
=> Add golangilint to CI

api/v1/slurmcluster_types.go, config/crd/bases/slurm.nebius.ai_slurmclusters.yaml, helm/soperator-crds/templates/slurmcluster-crd.yaml, helm/soperator/crds/slurmcluster-crd.yaml, internal/render/worker/container.go
Default DebugFlags are reduced to prevent job timeouts on large clusters.
preStop hooks are removed because, when jobs are suspended and workers are restarted, the hooks may deallocate workers still associated with suspended jobs. This leads to controller inconsistencies and failure to recover jobs.
Additionally, preStop hooks are unreliable during instance terminations and kernel panics, where they often do not execute.
=> NOISSUE: reduction of DebugFlags and removal of the preStop hook

fluxcd/environment/nebius-cloud/base/custom-configmaps-soperator/epilog.sh, fluxcd/environment/nebius-cloud/base/custom-configmaps-soperator/prolog.sh, helm/soperator-fluxcd/templates/dcgm-exporter.yaml, helm/soperator-fluxcd/templates/helmrepository.yaml, helm/soperator-fluxcd/values.yaml
This enabled installing the exporter separate from GPU Operator, which let's us configure [HPC job mapping](https://github.com/NVIDIA/dcgm-exporter/tree/main?tab=readme-ov-file#how-to-include-hpc-jobs-in-metric-labels) feature
https://github.com/nebius/soperator/issues/907
=> Adding DCGM Exporter to helm chart and values

fluxcd/environment/nebius-cloud/base/kustomization.yaml
```
k -n flux-system get helmreleases.helm.toolkit.fluxcd.io flux-system-soperator-fluxcd-backup-schedule -w
NAME                                           AGE    READY   STATUS
flux-system-soperator-fluxcd-backup-schedule   2d5h   True    Helm install succeeded for release k8up-system/k8up-schedule.v1 with chart raw@2.0.0
```
=> add crds k8up

internal/controller/reconciler/k8s_service.go, internal/controller/reconciler/k8s_service_test.go
This pull request enhances the `ServiceReconciler` in the Kubernetes controller by improving the patching logic for annotations and adding comprehensive unit tests to ensure correctness. The most important changes include leveraging the `maps.Copy` utility for annotation updates and introducing a new test suite for the `patch` function.
* Updated the `patch` function in `internal/controller/reconciler/k8s_service.go` to use `maps.Copy` for copying annotations, ensuring cleaner and safer handling of map operations. This includes initializing the destination annotations map only when necessary.
* Added the `maps` package import to support the new `maps.Copy` utility.
* Introduced a new test suite in `internal/controller/reconciler/k8s_service_test.go` to verify the behavior of the `patch` …
=> refactor(reconciler): simplify Service annotation merge with maps.Copy

.github/workflows/one_job.yml, cmd/exporter/main.go, images/soperator-exporter/soperator-exporter.dockerfile, internal/exporter/collector.go, internal/exporter/exporter.go
Initial version of the soperator exporter app. For now, it does two things:
- exposes a single metric
- does an API request which is not used by any metric so far
Infra for the app (the reconciler) will be provided separately.
Issue: #793
=> Add Soperator exporter app.

internal/exporter/collector.go, internal/exporter/collector_test.go
[#761](https://github.com/nebius/soperator/issues/761)
=> Do not lower case for slurm node state (for consistency with jobs).

.github/workflows/one_job.yml
Remove all cache steps from CI workflow to improve build performance by 52.4%.
Comprehensive testing across 21 builds showed that Go modules and build artifacts persist naturally on self-hosted runners, making remote caching pure overhead.
- Total build time: 25m 22s → 12m 5s
- All jobs 33-92% faster
- Build quality unchanged
- Simplified workflow with no cache dependencies
- Remove Cache go modules steps from all jobs
- Remove Save Cache steps
- Keep `cache: false` on setup-go
=> perf: optimize build performance by removing all caching

.github/workflows/one_job.yml, Makefile, helm/slurm-cluster/templates/slurm-cluster-cr.yaml, helm/slurm-cluster/values.yaml
This change enables the soperator exporter by default to provide Prometheus metrics collection out of the box. 
Together with changing the dashboard (https://github.com/nebius/nebius-solutions-library/pull/357), users will now see new dashboard in new installations.
Addresses this issue: https://github.com/nebius/soperator/issues/994
=> Use soperator exporter by default.

internal/exporter/collector.go, internal/exporter/collector_test.go, internal/slurmapi/node.go
- Rename state labels to use consistent state_ prefix:
- base_state -> state_base
- is_drain -> state_is_drain
- is_maintenance -> state_is_maintenance
- is_reserved -> state_is_reserved
- Rename compute_instance_id -> instance_id to be consistent with Slurm terms
- Add state labels to slurm_node_fails_total
- Rename slurm_active_node_gpu_seconds_total -> slurm_node_gpu_seconds_total and add the state labels
- Remove slurm_job_alloc_gpu_seconds_total metric entirely (will slurm_node_gpu_seconds_total with proper states instead)
=> Enhance node metrics with state labels and remove job GPU metric

cmd/exporter/main.go, internal/exporter/collector.go, internal/exporter/collector_test.go, internal/exporter/exporter.go, internal/render/exporter/container.go, internal/render/exporter/container_test.go
This PR removes the `soperator_cluster_info` metric and all associated `--soperator-version` flag usage from the soperator exporter.
- **Metric removal**: Removed `soperator_cluster_info` metric from the exporter collector
- **CLI flag removal**: Removed `--soperator-version` flag from the exporter binary  
- **Container configuration**: Removed `--soperator-version` from container args in Kubernetes deployments
- **Test updates**: Updated all tests to reflect the removal of the metric and flag
- **Code cleanup**: Removed unused fields and parameters throughout the codebase
The `soperator_cluster_info` metric provided operator version information, but this functionality will be superseded by [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics) in the future. Rather than …
=> Remove soperator_cluster_info metric and --soperator-version flag

internal/exporter/collector.go, internal/exporter/collector_test.go, internal/slurmapi/client.go, internal/slurmapi/fake/mock_client.go, internal/slurmapi/interface.go
Implements SLURM controller RPC metrics export functionality for monitoring controller performance.
- **RPC Metrics by Message Type**: Exports `slurm_controller_rpc_calls_total` and `slurm_controller_rpc_duration_seconds_total` metrics with `message_type` labels
- **RPC Metrics by User**: Exports `slurm_controller_rpc_user_calls_total` and `slurm_controller_rpc_user_duration_seconds_total` metrics with `user` and `user_id` labels  
- **Controller Metrics**: Exports `slurm_controller_server_thread_count` gauge metric
```
slurm_controller_rpc_calls_total{message_type="MESSAGE_NODE_REGISTRATION_STATUS"} 14
slurm_controller_rpc_calls_total{message_type="REQUEST_JOB_INFO"} 370
slurm_controller_rpc_calls_total{message_type="REQUEST_NODE_INFO"} 742 …
```
=> Add controller RPC metrics export

images/common/spank-nccl-debug/README.md, images/common/spank-nccl-debug/src/snccld.c, images/common/spank-nccl-debug/src/snccld_args.h
This PR ensures that if the user has already set the `NCCL_DEBUG` environment variable, we automatically enable stdout logging (`out-stdout=1`), updates some function formatting, and documents the new behaviour.
- Detect and force `out_stdout` when `NCCL_DEBUG` is set in `slurm_spank_user_init`
- Reformat `snccld_substitute_hostname` calls with `clang-format`
- Add an important note in `README.md` about forced stdout when `NCCL_DEBUG` is user-provided
=> Set `out-stdout=1` if user provided `NCCL_DEBUG` on their own

internal/controller/clustercontroller/controller.go, internal/render/common/configmap.go, internal/render/controller/container.go, internal/render/controller/service.go
Here’s a summary of the changes in this pull request:
**internal/controller/clustercontroller/controller.go**
- Refactors the reconciliation logic for controller services to create a separate Kubernetes Service for each controller pod (per-pod services) based on the number of replicas.
- Adds logic to clean up excess services that are no longer needed.
- Removes repetitive error logging statements (error logging is now mostly handled by returning errors).
- Updates usage of the Service rendering function to support per-pod labels and naming.
**internal/render/common/configmap.go**
- Changes how SlurmctldHost entries are generated in config files:
- Uses the pattern `<statefulset-name>-<index>` for both host and FQDN, instead of relying on the previous `naming.BuildServiceHostFQDN` …
=> Fix Slurm controller failover #1268

images/common/spank-nccl-debug/src/snccld.c, images/common/spank-nccl-debug/src/snccld_state.c, images/common/spank-nccl-debug/src/snccld_util_dir_file.c, images/common/spank-nccl-debug/src/snccld_util_dir_file.h, images/common/spank-nccl-debug/src/snccld_util_oplock.c
Using umask is too broad and error-prone to umask not being returned to the previous mask.
This PR replaces the umask set/return logic with dedicated chmod calls for particular files and folders along with support of file/directory creation as root/user.
=> [nccl-debug] Use chmod instead of umask

api/v1/slurmcluster_types.go, api/v1/zz_generated.deepcopy.go, config/crd/bases/slurm.nebius.ai_slurmclusters.yaml, helm/soperator-crds/templates/slurmcluster-crd.yaml, helm/soperator/crds/slurmcluster-crd.yaml, internal/render/worker/statefulset.go, internal/values/slurm_worker.go
Added the ability to specify the maximum number of `maxUnavailable` pods during a rolling upgrade, and, if possible, to preload the image and patch the pod spec with the new image without needing to recreate the pod.
Fixes #1390
=> [slurmcluster] maxUnavalaible for workes and support pre install images

internal/controller/reconciler/k8s_statefulset.go, internal/controller/reconciler/reconciler.go
Fix StatefulSet update error by ensuring resourceVersion is preserved
Resolves the "metadata.resourceVersion: Invalid value: 0x0: must be specified for an update" error when reconciling StatefulSets by properly handling the resourceVersion field during updates.
#[#1417](https://github.com/nebius/soperator/issues/1417)
=> fix issue with metadata.resourceVersion: Invalid value: 0x0: must be specified for an Patch in ASTS

cmd/exporter/main.go, internal/slurmapi/client.go
Add a minimal, backward-compatible path to run the exporter against a **standalone Slurm cluster** (`slurmrestd` with `rest_auth/jwt`)—no Kubernetes required.
- **New Flags**
- `--standalone`: skip k8s client/JWT flow.
- `--static-token` (optional): alternative to env; CLI still has highest precedence.
- **Auth**
- Prefer **`SLURM_EXPORTER_TOKEN`** from the environment for REST calls.
- Do **not** rely on `SLURM_JWT` (kept out to avoid collisions with Slurm internals).
- **HTTP client**
- Use `Header.Set` instead of `Header.Add` for `X-SLURM-USER-TOKEN` (and `Content-Type`) to avoid duplicate headers on retries.
- **Docs**
- README section describing standalone mode usage, and troubleshooting.
- Verified with Slurm 24.05.x + `slurmrestd` **v0.0.40**.
=> Standalone Slurm exporter - No Kubernetes needed

internal/controller/reconciler/k8s_configmap.go
This PR fixes a potential nil pointer dereference when patching ConfigMaps that have empty or nil labels by ensuring the Labels map is initialized before copying labels from the source.
Adds nil check and initialization for the Labels map in the ConfigMap patch operation
Prevents runtime panics when copying labels to ConfigMaps with nil Labels
=> fix patch cm with empty labels

helm/soperator/values.yaml, helm/soperatorchecks/values.yaml
The soperator controller was missing configurable command-line flags for key operational parameters like logging, reconciliation timeouts, and node management behavior. This made it difficult to tune the controller's behavior for different environments and requirements without rebuilding the image.
Added comprehensive command-line flags to the soperator controller with sensible defaults:
- `--log-format` and `--log-level` for logging configuration
- `--reconcile-timeout` and `--max-concurrent-reconciles` for performance tuning
- `--cache-sync-timeout` for cache synchronization control
- `--enable-node-replacement` for node replacement controller toggle
- `--not-ready-timeout` and `--delete-not-ready-nodes` for automated node cleanup
These flags are now exposed in the Helm chart …
=> add delete-not-ready-nodes=true by default in helm
